export const manifest = {
    bundles: [
        {
            name: 'cards',
            assets: [
                //cards
                { alias: 'spade_1', src: '/cards/spade_1.png' },
                { alias: 'spade_2', src: '/cards/spade_2.png' },
                { alias: 'spade_3', src: '/cards/spade_3.png' },
                { alias: 'spade_4', src: '/cards/spade_4.png' },
                { alias: 'spade_5', src: '/cards/spade_5.png' },
                { alias: 'spade_6', src: '/cards/spade_6.png' },
                { alias: 'spade_7', src: '/cards/spade_7.png' },
                { alias: 'spade_8', src: '/cards/spade_8.png' },
                { alias: 'spade_9', src: '/cards/spade_9.png' },
                { alias: 'spade_10', src: '/cards/spade_10.png' },
                { alias: 'spade_jack', src: '/cards/spade_jack.png' },
                { alias: 'spade_king', src: '/cards/spade_king.png' },
                { alias: 'spade_queen', src: '/cards/spade_queen.png' },

                { alias: 'club_1', src: '/cards/club_1.png' },
                { alias: 'club_2', src: '/cards/club_2.png' },
                { alias: 'club_3', src: '/cards/club_3.png' },
                { alias: 'club_4', src: '/cards/club_4.png' },
                { alias: 'club_5', src: '/cards/club_5.png' },
                { alias: 'club_6', src: '/cards/club_6.png' },
                { alias: 'club_7', src: '/cards/club_7.png' },
                { alias: 'club_8', src: '/cards/club_8.png' },
                { alias: 'club_9', src: '/cards/club_9.png' },
                { alias: 'club_10', src: '/cards/club_10.png' },
                { alias: 'club_jack', src: '/cards/club_jack.png' },
                { alias: 'club_queen', src: '/cards/club_queen.png' },
                { alias: 'club_king', src: '/cards/club_king.png' },

                // Diamonds
                { alias: 'diamond_1', src: '/cards/diamond_1.png' },
                { alias: 'diamond_2', src: '/cards/diamond_2.png' },
                { alias: 'diamond_3', src: '/cards/diamond_3.png' },
                { alias: 'diamond_4', src: '/cards/diamond_4.png' },
                { alias: 'diamond_5', src: '/cards/diamond_5.png' },
                { alias: 'diamond_6', src: '/cards/diamond_6.png' },
                { alias: 'diamond_7', src: '/cards/diamond_7.png' },
                { alias: 'diamond_8', src: '/cards/diamond_8.png' },
                { alias: 'diamond_9', src: '/cards/diamond_9.png' },
                { alias: 'diamond_10', src: '/cards/diamond_10.png' },
                { alias: 'diamond_jack', src: '/cards/diamond_jack.png' },
                { alias: 'diamond_queen', src: '/cards/diamond_queen.png' },
                { alias: 'diamond_king', src: '/cards/diamond_king.png' },

                // Hearts
                { alias: 'heart_1', src: '/cards/heart_1.png' },
                { alias: 'heart_2', src: '/cards/heart_2.png' },
                { alias: 'heart_3', src: '/cards/heart_3.png' },
                { alias: 'heart_4', src: '/cards/heart_4.png' },
                { alias: 'heart_5', src: '/cards/heart_5.png' },
                { alias: 'heart_6', src: '/cards/heart_6.png' },
                { alias: 'heart_7', src: '/cards/heart_7.png' },
                { alias: 'heart_8', src: '/cards/heart_8.png' },
                { alias: 'heart_9', src: '/cards/heart_9.png' },
                { alias: 'heart_10', src: '/cards/heart_10.png' },
                { alias: 'heart_jack', src: '/cards/heart_jack.png' },
                { alias: 'heart_queen', src: '/cards/heart_queen.png' },
                { alias: 'heart_king', src: '/cards/heart_king.png' },


                { alias: 'BACK', src: '/cards/back.png' },

                //chips
                { alias: 'chip_1', src: '/chips/chip_1.png' },
                { alias: 'chip_5', src: '/chips/chip_5.png' },
                { alias: 'chip_10', src: '/chips/chip_10.png' },
                { alias: 'chip_25', src: '/chips/chip_25.png' },
                { alias: 'chip_50', src: '/chips/chip_50.png' },
                { alias: 'chip_100', src: '/chips/chip_100.png' },

                //button icons
                { alias: 'btn_clear', src: '/buttons/clear.png' },
                { alias: 'btn_deal', src: '/buttons/deal.png' },
                { alias: 'btn_deal2', src: '/buttons/deal2.png' },
                { alias: 'btn_double', src: '/buttons/double2.png' },
                { alias: 'btn_undo', src: '/buttons/undo.png' },
                { alias: 'btn_stand', src: '/buttons/stand.png' },
                { alias: 'btn_new_game', src: '/buttons/new_game.png' },
                { alias: 'btn_hand', src: '/buttons/hand.png' },
                { alias: 'btn_menu', src: '/buttons/menu.png' },
                { alias: 'btn_volume_on', src: '/buttons/volume-1.png' },
                { alias: 'btn_volume_low', src: '/buttons/volume-2.png' },
                { alias: 'btn_volume_off', src: '/buttons/volume-x.png' },
                { alias: 'btn_2x', src: '/buttons/2x.png' },
                { alias: 'btn_insurance', src: '/buttons/btn_insurance.png' },
                { alias: 'btn_split', src: '/buttons/btn_split.png' },
            ],
        },
    ],
}